name: Update Tunnel
description: Updates the Cloudflared Tunnel to work with a new provider

inputs:
  SERVICE_URL:
    description: 'The URL of the service to route traffic to'
    required: true
  CLOUDFLARE_API_TOKEN:
    description: 'Cloudflare API token'
    required: true
  CLOUDFLARE_ACCOUNT_ID:
    description: 'Cloudflare account ID'
    required: true
  CLOUDFLARE_TUNNEL_ID:
    description: 'Cloudflare tunnel ID'
    required: true
  HOSTNAME:
    description: 'The hostname to route traffic to'
    required: false

runs:
  using: composite
  steps:
    - name: Update Tunnel Configuration
      shell: bash
      env:
        SERVICE_URL: ${{ inputs.SERVICE_URL }}
        CLOUDFLARE_API_TOKEN: ${{ inputs.CLOUDFLARE_API_TOKEN }}
        CLOUDFLARE_ACCOUNT_ID: ${{ inputs.CLOUDFLARE_ACCOUNT_ID }}
        CLOUDFLARE_TUNNEL_ID: ${{ inputs.CLOUDFLARE_TUNNEL_ID }}
        HOSTNAME: ${{ inputs.HOSTNAME }}
      run: |
        TUNNEL_CONFIG='{
          "config": {
            "ingress": [
              {
                "service": "https://chuckfinca--llm-server-production-fastapi-app.modal.run",
                "hostname": "api.appsimple.io",
                "originRequest": {
                  "connectTimeout": 30,
                  "noHappyEyeballs": false,
                  "keepAliveTimeout": 60,
                  "keepAliveConnections": 10,
                  "http2Origin": true,
                  "tcpKeepAlive": 30,
                  "timeout": 60
                }
              },
              {
                "service": "http_status:404"
              }
            ]
          }
        }'
        
        echo "Updating tunnel configuration..."
        
        UPDATE_RESPONSE=$(curl -s -X PUT \
          "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/cfd_tunnel/${CLOUDFLARE_TUNNEL_ID}/configurations" \
          -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
          -H "Content-Type: application/json" \
          --data "$TUNNEL_CONFIG")
        
        if echo $UPDATE_RESPONSE | jq -e '.success == true' > /dev/null; then
          echo "✅ Tunnel configuration updated successfully"
        else
          echo "❌ Failed to update tunnel configuration"
          echo $UPDATE_RESPONSE | jq '.'
          exit 1
        fi