# Use Python 3.9 slim image as base
FROM python:3.9-slim

# Set working directory
WORKDIR /app
COPY . .

# Install dependencies
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/* && \
    pip install --no-cache-dir '.[modal]'