name: Deploy to Modal

on:
  push:
    tags: 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Modal
        run: |
          python -m pip install --upgrade pip
          pip install modal
        
      - name: Login to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_SECRET }}
        run: |
          modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
      - name: Create Modal Secrets
        run: |
          modal secret create llm-server-${{ github.event.inputs.environment || 'staging' }}-secrets \
            OPENAI_API_KEY="${{ secrets.OPENAI_DEV }}" \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_DEV }}" \
            HUGGINGFACE_API_KEY="${{ secrets.HF_DEV }}" \
            LLM_SERVER_API_KEY="${{ secrets.LLM_SERVER }}" \
            --force
            
      - name: Deploy to Modal
        run: modal deploy deploy_modal_app.py --name llm-server-${{ github.event.inputs.environment || 'staging' }}
      
      - name: Get Modal Deployment URL
        id: modal-url
        run: |
          MODAL_URL=$(modal app show llm-server-${{ github.event.inputs.environment || 'staging' }} --url)
          echo "MODAL_URL=${MODAL_URL}" >> $GITHUB_ENV

      - name: Update Cloudflare Tunnel
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
          TUNNEL_ID: ${{ secrets.CLOUDFLARE_TUNNEL }}
        run: |
          # Update tunnel configuration using Cloudflare API
          curl -X PUT "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT }}/tunnels/${TUNNEL_ID}/configurations" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data '{
              "config": {
                "ingress": [
                  {
                    "hostname": "api.appsimple.io",
                    "service": "'"${MODAL_URL}"'"
                  }
                ]
              }
            }'