name: Deploy to Modal

on:
  push:
    tags: 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal jq

      - name: Login to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_SECRET }}
        run: |
          modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
      
      - name: Pass Secrets to Modal
        run: |
          modal secret create app-secrets \
            OPENAI_API_KEY="${{ secrets.OPENAI_DEV }}" \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_DEV }}" \
            HUGGINGFACE_API_KEY="${{ secrets.HF_DEV }}" \
            LLM_SERVER_API_KEY="${{ secrets.LLM_SERVER }}" \
            APP_ENV="${{ github.event.inputs.environment || 'staging' }}" \
            --force
                   
      - name: Deploy to Modal
        run: |
          echo "Deploying with name: llm-server-${{ github.event.inputs.environment || 'staging' }}"
          modal deploy deploy_modal_app.py --name llm-server-${{ github.event.inputs.environment || 'staging' }}
      
      - name: Get Modal Deployment URL
      id: modal-url
      env:
        MODAL_TOKEN_ID: ${{ secrets.MODAL_ID }}
        MODAL_TOKEN_SECRET: ${{ secrets.MODAL_SECRET }}
      run: |
        APP_NAME="llm-server-${{ github.event.inputs.environment || 'staging' }}"
        MODAL_URL="https://chuckfinca--${APP_NAME}-fastapi-app.modal.run"
        echo "modal_url=${MODAL_URL}" >> $GITHUB_OUTPUT

      - name: Update Cloudflare Tunnel
        uses: ./.github/workflows/update-tunnel.yml
        with:
          service_url: ${{ steps.modal-url.outputs.modal_url }}
        secrets:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          CLOUDFLARE_TUNNEL_ID: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}