name: Deploy to Modal

on:
  push:
    tags: 'v*'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production

jobs:
  deploy:
    name: Deploy to ${{ github.event.inputs.environment || 'staging' }}
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install modal jq

      - name: Login to Modal
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_SECRET }}
        run: |
          modal token set --token-id $MODAL_TOKEN_ID --token-secret $MODAL_TOKEN_SECRET
      
      - name: Create Modal Secrets
        run: |
          modal secret create llm-server-${{ github.event.inputs.environment || 'staging' }}-secrets \
            OPENAI_API_KEY="${{ secrets.OPENAI_DEV }}" \
            ANTHROPIC_API_KEY="${{ secrets.ANTHROPIC_DEV }}" \
            HUGGINGFACE_API_KEY="${{ secrets.HF_DEV }}" \
            LLM_SERVER_API_KEY="${{ secrets.LLM_SERVER }}" \
            --force
            
      - name: Deploy to Modal
        run: |
          echo "Deploying with name: llm-server-${{ github.event.inputs.environment || 'staging' }}"
          modal deploy deploy_modal_app.py --name llm-server-${{ github.event.inputs.environment || 'staging' }}

      - name: Get Modal Deployment URL
        id: modal-url
        env:
          MODAL_TOKEN_ID: ${{ secrets.MODAL_ID }}
          MODAL_TOKEN_SECRET: ${{ secrets.MODAL_SECRET }}
        run: |
          APP_NAME="llm-server-${{ github.event.inputs.environment || 'staging' }}"
          
          MODAL_URL="https://chuckfinca--${APP_NAME}-fastapi-app.modal.run"
          echo "Setting MODAL_URL to: $MODAL_URL"
          echo "MODAL_URL=${MODAL_URL}" >> $GITHUB_ENV
      
      - name: Verify Cloudflare API Token
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
        run: |
          echo "Verifying API token permissions..."
          RESPONSE=$(curl -s -X GET "https://api.cloudflare.com/client/v4/user/tokens/verify" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}")
          
          echo "Token verification response:"
          echo $RESPONSE | jq '.'
          
          if echo $RESPONSE | jq -e '.success == true' > /dev/null; then
            echo "✅ Token is valid"
          else
            echo "❌ Token verification failed"
            exit 1
          fi
      
      - name: Update Cloudflare Tunnel
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
          CLOUDFLARE_ACCOUNT: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          TUNNEL_ID: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
        run: |
          echo "Updating tunnel configuration..."
          
          TUNNEL_CONFIG='{
            "config": {
              "ingress": [
                {
                  "hostname": "api.appsimple.io",
                  "service": "'${MODAL_URL}'",
                  "originRequest": {
                    "connectTimeout": "5s"
                  }
                },
                {
                  "service": "http_status:503",
                  "originResponse": {
                    "headers": {
                      "Retry-After": ["10"],
                      "X-Error-Message": ["Service starting, please retry shortly"]
                    }
                  }
                }
              ]
            }
          }'
          
          echo "Using configuration:"
          echo $TUNNEL_CONFIG | jq '.'
          
          UPDATE_RESPONSE=$(curl -v -X PUT \
            "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT}/cfd_tunnel/${TUNNEL_ID}/configurations" \
            -H "Authorization: Bearer ${CLOUDFLARE_API_TOKEN}" \
            -H "Content-Type: application/json" \
            --data "$TUNNEL_CONFIG")
          
          echo "Update response:"
          echo $UPDATE_RESPONSE | jq '.'
          
          if echo $UPDATE_RESPONSE | jq -e '.success == true' > /dev/null; then
            echo "✅ Configuration update successful"
          else
            echo "❌ Configuration update failed"
            exit 1
          fi