name: Publish Python Package to PyPI

on:
  push:
    tags:
      - 'v*' # Trigger this workflow when a new tag like 'v0.3.0' is pushed

jobs:
  build-and-publish:
    name: Build and publish Python package to PyPI
    runs-on: ubuntu-latest
    # id-token permission is not needed for the token-based approach
    # permissions:
    #   id-token: write 
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install build dependencies
        run: python -m pip install --upgrade build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          # Use a specific API token for TestPyPI, stored in a different secret
          password: ${{ secrets.PYPI_API_TOKEN }}
          # Point to the TestPyPI repository
          repository-url: https://test.pypi.org/legacy/