name: Update Cloudflare Tunnel

on:
  workflow_call:
    inputs:
      service_url:
        required: true
        type: string
        description: 'The URL of the deployed service'

jobs:
  update-tunnel:
    runs-on: ubuntu-latest
    steps:
      - name: Update Tunnel Configuration
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT }}
          CLOUDFLARE_TUNNEL_ID: ${{ secrets.CLOUDFLARE_TUNNEL_ID }}
        run: |
          TUNNEL_CONFIG='{
            "config": {
              "ingress": [
                {
                  "hostname": "api.appsimple.io",
                  "service": "${{ inputs.service_url }}",
                  "originRequest": {
                    "connectTimeout": 10,
                    "noHappyEyeballs": false,
                    "keepAliveTimeout": 30,
                    "keepAliveConnections": 10
                  }
                },
                {
                  "service": "http_status:404"
                }
              ]
            }
          }'
          
          echo "Updating tunnel configuration..."
          
          UPDATE_RESPONSE=$(curl -s -X PUT \
            "https://api.cloudflare.com/client/v4/accounts/${{ secrets.CLOUDFLARE_ACCOUNT_ID }}/cfd_tunnel/${{ secrets.CLOUDFLARE_TUNNEL_ID }}/configurations" \
            -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            --data "$TUNNEL_CONFIG")
          
          if echo $UPDATE_RESPONSE | jq -e '.success == true' > /dev/null; then
            echo "✅ Tunnel configuration updated successfully"
          else
            echo "❌ Failed to update tunnel configuration"
            echo $UPDATE_RESPONSE | jq '.'
            exit 1
          fi